---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dragonfly-operator.fullname" . }}
  labels:
    app.kubernetes.io/component: rbac
    {{- include "dragonfly-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dragonfly-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "dragonfly-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
