apiVersion: v1
kind: Service
metadata:
  name: {{ include "dragonfly-operator.fullname" . }}-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: dragonfly-operator
    app.kubernetes.io/part-of: dragonfly-operator
    control-plane: dragonfly-operator
  {{- include "dragonfly-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: dragonfly-operator
  {{- include "dragonfly-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}