---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dragonfly-operator.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: rbac
    {{- include "dragonfly-operator.labels" . | nindent 4 }}
