apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: dragonfly-operator
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: dragonfly-operator-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: dragonfly-operator
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
  name: dragonfly-operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: dragonfly-operator
