apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: dragonfly-operator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dragonfly-operator
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
  name: dragonfly-operator
  namespace: system
