apiVersion: dragonfly.pborn.eu/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly-sample
spec:
  # TODO(user): edit the following value to ensure the number
  # of Pods/Instances your Operand must have on cluster
  size: 1

